### ISSUE TITLE
Using an already existing URI path leads to unresolvable error

### ISSUE THREAD

**Issue by bwaidelich** [flownative/neos-customdocumenturirouting#4]
When using this package in addition to the regular Neos routing this can lead to an "editor deadlock":
Setting a uriPathPropertyName to an URL that is already a valid Neos URL.

In this case one of two things seem to happen:
* An error occurs and the currently edited node is not navigatable in the backend any longer
* The node that previously matched the URL is no longer navigatable 

Maybe it's possible to replicate/invoke the custom `FrontendNodeRoutePartHandler` logic to find out if there are collisions!?

**Comment by bwaidelich** [comment]
I think I have a working solution for this. Waiting for #6 to get merged to avoid conflicts

**Comment by kdambekalns** [comment]
#6 is merged, looking forward to the fix for this one! :)
